### ISSUE TITLE
Error using workoffline REREG

### ISSUE THREAD

**Issue by robcolby** [gitmachtl/scripts#29]
Hi,
I have an issue when executing an offline transaction with Era discovery. I ran 
- 05a to create the pool.json file
- Edited the JSON file to include my changes 
- 05c <pool> <wallet> REREG

Then when I brought offlinetransfer to my online server, I tried to execute and got this error:
ERROR - Online(alonzo) and Offline(auto) Era mismatch!

I tried to review the code in the workoffline script and in the JSON file, and considered just manually editing the JSON to use alonzo instead of auto, but figured I'd submit this first and see if you have a BKM just in case I screw something up.

**Comment by robcolby** [comment]
BTW, outcome when I run "execute":

Version-Info: cli 1.30.1 / node 1.30.1          Scripts-Mode: online

Checking Content of the offlineFile: offlineTransfer.json

Protocol-Parameters: present           Protocol-Era: auto
    History-Entries: 45
        Last-Action: extracted file 'myPool.metadata.json' (Sat, 06 Nov 2021 15:15:57 -0700)
    Offline Version: cli 1.30.1

 <addresses and transaction not shown>

--------------

Here is my transaction in the offline JSON file (with names and addresses removed)


<   "transactions": [
<     {
<       "date": "Sat, 06 Nov 2021 15:09:14 -0700",
<       "type": "PoolReRegistration",
<       "era": "auto",
<       "fromAddr": "<removed>",
<       "sendFromAddr": "<removed>",
<       "toAddr": "<removed>",
<       "sendToAddr": "<removed>",
<       "poolMetaTicker": "<removed>",
<       "regProtectionKey": "",
<       "poolMetaUrl": "https://<removed>/pool.metadata.json",
<       "poolMetaHash": "<removed>",
<       "txJSON": {
<         "type": "Tx MaryEra",
<         "description": "",
<         "cborHex": "<removed>"
<       }
<     }
<   ]

**Comment by robcolby** [comment]
I worked around the issue for now by removing "exit 1" from this line in 01_workoffline:

if [[ ! "${transactionEra}" == "$(get_NodeEra)" ]]; then echo -e "\e[35mERROR - Online($(get_NodeEra)) and Offline(${transactionEra}) Era mismatch!\e[0m\n"; exit 1; fi


I put the "exit 1" back after what appeared to be a successful execution of REREG

**Comment by gitmachtl** [comment]
thx @robcolby yes i think we can lift the restriction here if an offline transaction was initiated via an auto-era transaction. this is the case when the offline machine does not know the era it is currently in it. its a safety feature from the past and only an additional check. i'll look into it, thx for the discovery!

**Comment by gitmachtl** [comment]
hmm... it could be an issue with 1.30.1, because sometimes 1.30.1 is not reporting back queries like it should. only an empty query is reported back. in this case, the outcome would be "auto". can you check the "protocol" section in your offlineTransfer.json please. if your online node is synced when you do an "add", "new" or "clear" it updates the current protocol data in the offlineTransfer.json. so i guess you have "auto" in the .protocol.era key in there?

**Comment by robcolby** [comment]
I actually did check the protocol section of offlineTransfer at the time, it showed "auto" as well. I wasn't sure if I should manually edit that or not.

I suspect you are correct in that 1.30.1 is not reporting as it should, because I actually did another REREG shortly after this and it worked the second time without me having to edit 01_workoffline. 

I also just checked my offlineTrasfer file and can see it now has the correct Era at the top.

**Comment by gitmachtl** [comment]
hi, actually i have the pool update in offline mode as a full example in the readme, you can find it here:
https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet#update-stakepool-parameters-on-the-blockchain-in-offline-mode

i will close this issue for now, because its a node issue. 1.31.0 does not show the behaviour.
